### PR TITLE
Bump MathComp version to >= 1.12.0

### LINKED ISSUE #2: Bump Coq/Mathcomp versions
In order to use Apery as a benchmark for new proof automation facilities, it has to support Coq 8.13 and MathComp 1.12.0 first. I will do this, and open this issue just not to duplicate our effort.

### PR DESCRIPTION
**Pull request by pi8027**
This PR makes apery compatible with MathComp 1.12.0 and later. It also cleans up proof scripts as preliminary work for #4. This PR itself does not add any extra dependency or enhance the proof automation facility.

Closes #2

### CODE REVIEW

**Comment by pi8027** [comment]
CoqEAL/CoqEAL#38 should fix the CI failure with coq.dev.

**Comment by pi8027** [comment]
Waiting for a fix for multinomials.

**Comment by CohenCyril** [comment]
The CI failure is spurious (and should eventually be solved by https://github.com/math-comp/multinomials/pull/53 and a release AFAIU).
@amahboubi do you have time to review this? Do you want someone else to review it?

**Comment by pi8027** [comment]
CI green.

**Comment by amahboubi** [comment]
Many thanks @pi8027 for this amazing work. I do not have time for reviewing such a PR right away, but I am of course fine with a review by someone else, or even with a merge after minimal verifications.

**Review by CohenCyril — APPROVED** [review]
@amahboubi 
> Many thanks @pi8027 for this amazing work. I do not have time for reviewing such a PR right away, but I am of course fine with a review by someone else, or even with a merge after minimal checks.

I did a minimal check, and I approve.

**Comment by amahboubi** [comment]
Thanks a lot!

**Pull request merged**
